import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Eye, Database, Share2, Clock, UserCheck, Cookie, Mail } from 'lucide-react';

type Section = 'collect' | 'use' | 'sharing' | 'retention' | 'rights' | 'cookies' | 'contact';

const sections: { id: Section; label: string; icon: React.ElementType }[] = [
  { id: 'collect',   label: 'Information We Collect', icon: Database   },
  { id: 'use',       label: 'How We Use Your Data',   icon: Eye        },
  { id: 'sharing',   label: 'Data Sharing',           icon: Share2     },
  { id: 'retention', label: 'Data Retention',         icon: Clock      },
  { id: 'rights',    label: 'Your Rights',            icon: UserCheck  },
  { id: 'cookies',   label: 'Cookies & Analytics',    icon: Cookie     },
  { id: 'contact',   label: 'Contact Us',             icon: Mail       },
];

export const PrivacyPage: React.FC = () => {
  const [active, setActive] = useState<Section>('collect');

  return (
    <div className="max-w-5xl mx-auto pb-20">
      {/* Header */}
      <div className="mb-10">
        <Link to="/" className="inline-flex items-center gap-2 text-slate-500 hover:text-white text-sm mb-6 transition-colors">
          <ArrowLeft className="w-4 h-4" /> Back
        </Link>
        <div className="flex items-center gap-3 mb-3">
          <div className="w-10 h-10 rounded-xl bg-brand-blue/10 border border-brand-blue/20 flex items-center justify-center">
            <Eye className="w-5 h-5 text-brand-blue" />
          </div>
          <h1 className="text-3xl font-extrabold text-white">Privacy Policy</h1>
        </div>
        <p className="text-slate-400 text-sm max-w-xl">
          Your privacy matters to us. This policy explains what data we collect, how we use it, and the choices you have.
        </p>
        <p className="text-slate-600 text-xs mt-2">Effective date: February 1, 2026 · Last updated: February 2026</p>
      </div>

      <div className="flex gap-8">
        {/* Sidebar Nav */}
        <aside className="w-48 flex-shrink-0 hidden md:block">
          <nav className="sticky top-6 space-y-1">
            {sections.map(s => {
              const Icon = s.icon;
              return (
                <button
                  key={s.id}
                  onClick={() => setActive(s.id)}
                  className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm font-medium transition-all text-left ${
                    active === s.id
                      ? 'bg-dark-700 text-white border border-dark-600'
                      : 'text-slate-500 hover:text-slate-300 hover:bg-dark-800'
                  }`}
                >
                  <Icon className={`w-4 h-4 flex-shrink-0 ${active === s.id ? 'text-brand-blue' : ''}`} />
                  <span className="text-xs">{s.label}</span>
                </button>
              );
            })}
          </nav>
          <div className="mt-6 pt-4 border-t border-dark-700 space-y-2">
            <Link to="/policy" className="block text-xs text-slate-600 hover:text-slate-400 transition-colors">Community Policy</Link>
            <Link to="/terms" className="block text-xs text-slate-600 hover:text-slate-400 transition-colors">Terms of Service</Link>
          </div>
        </aside>

        {/* Mobile Nav */}
        <div className="md:hidden w-full mb-6 flex gap-2 overflow-x-auto pb-2">
          {sections.map(s => {
            const Icon = s.icon;
            return (
              <button
                key={s.id}
                onClick={() => setActive(s.id)}
                className={`flex-shrink-0 flex items-center gap-2 px-3 py-2 rounded-xl text-xs font-bold transition-all ${
                  active === s.id ? 'bg-dark-700 text-white border border-dark-600' : 'bg-dark-800 text-slate-500'
                }`}
              >
                <Icon className="w-3.5 h-3.5" />
                {s.label}
              </button>
            );
          })}
        </div>

        {/* Content */}
        <main className="flex-1 min-w-0">

          {active === 'collect' && (
            <Section title="Information We Collect" icon={Database}>
              <P>We collect information you provide directly to us, information generated by your use of the Platform, and limited technical data from your device.</P>
              <H3>Account Information</H3>
              <P>When you create an account, we collect your email address, display name, and password (stored in encrypted form). You may optionally provide a profile photo and bio.</P>
              <H3>Usage Data</H3>
              <P>We automatically collect data about how you interact with the Platform, including pages visited, posts viewed, articles read, likes given, and comments made. This data powers features like XP tracking, personalized recommendations, and analytics.</P>
              <H3>Community Content</H3>
              <P>Any content you post — including forum posts, comments, and profile information — is stored on our servers and may be visible to other users according to your privacy settings.</P>
              <H3>Device & Technical Data</H3>
              <P>We collect basic technical information including your browser type, operating system, IP address, and device identifiers. This is used for security, debugging, and improving Platform performance.</P>
              <Callout type="info">We do not collect sensitive personal information such as financial data directly. Payments are processed through secure third-party payment processors.</Callout>
            </Section>
          )}

          {active === 'use' && (
            <Section title="How We Use Your Information" icon={Eye}>
              <P>We use the information we collect to provide, maintain, and improve the Platform, and to communicate with you about your account and our services.</P>
              <H3>Core Service Delivery</H3>
              <ul className="space-y-2 text-slate-400 text-sm ml-4">
                {[
                  'Authenticating your identity and maintaining your account',
                  'Processing membership subscriptions and managing tier access',
                  'Tracking XP points and enforcing community thresholds',
                  'Delivering personalized content recommendations',
                  'Sending notifications about activity on your posts',
                ].map((item, i) => (
                  <li key={i} className="flex items-start gap-2">
                    <span className="text-green-500 mt-0.5">✓</span>
                    <span>{item}</span>
                  </li>
                ))}
              </ul>
              <H3>Safety & Moderation</H3>
              <ul className="space-y-2 text-slate-400 text-sm ml-4">
                {[
                  'Detecting and preventing spam, fraud, and abuse',
                  'Enforcing community policies and moderating content',
                  'Investigating reports of policy violations',
                  'Protecting the security and integrity of the Platform',
                ].map((item, i) => (
                  <li key={i} className="flex items-start gap-2">
                    <span className="text-green-500 mt-0.5">✓</span>
                    <span>{item}</span>
                  </li>
                ))}
              </ul>
              <H3>Platform Improvement</H3>
              <P>We analyze aggregated usage patterns to understand how the Platform is used, identify areas for improvement, and develop new features. This analysis uses anonymized or aggregated data wherever possible.</P>
              <Callout type="info">We do not use your data to serve third-party advertisements. Toupee4U does not sell advertising space or allow advertisers to target you based on your activity.</Callout>
            </Section>
          )}

          {active === 'sharing' && (
            <Section title="Data Sharing" icon={Share2}>
              <H3>We Do Not Sell Your Data</H3>
              <P>We do not sell, rent, or trade your personal information to third parties for their marketing purposes. Period.</P>
              <H3>Service Providers</H3>
              <P>We share data with trusted third-party service providers who assist us in operating the Platform. These include:</P>
              <div className="space-y-3 mt-3">
                {[
                  { name: 'Firebase / Google Cloud', purpose: 'Authentication, database storage, and hosting', icon: '🔥' },
                  { name: 'Payment Processor',        purpose: 'Secure processing of subscription payments',   icon: '💳' },
                  { name: 'Analytics Services',       purpose: 'Aggregated usage analytics and error tracking', icon: '📊' },
                ].map(provider => (
                  <div key={provider.name} className="flex items-start gap-3 p-3 bg-dark-900 rounded-xl border border-dark-700">
                    <span className="text-lg">{provider.icon}</span>
                    <div>
                      <p className="text-white text-sm font-semibold">{provider.name}</p>
                      <p className="text-slate-500 text-xs mt-0.5">{provider.purpose}</p>
                    </div>
                  </div>
                ))}
              </div>
              <P>All service providers are contractually required to protect your data and use it only for the specific services they provide to us.</P>
              <H3>Legal Requirements</H3>
              <P>We may disclose your information if required to do so by law, court order, or governmental authority, or if we believe disclosure is necessary to protect the rights, property, or safety of Toupee4U, our users, or others.</P>
              <Callout type="warning">In the event of a merger, acquisition, or sale of assets, your data may be transferred to the acquiring entity, subject to the same privacy protections described in this policy.</Callout>
            </Section>
          )}

          {active === 'retention' && (
            <Section title="Data Retention" icon={Clock}>
              <P>We retain your personal data for as long as your account is active or as needed to provide you with services.</P>
              <H3>Account Data</H3>
              <P>Your account data is retained for the duration of your account. If you delete your account, we will remove your personal information within 30 days, except where retention is required by law or legitimate business purposes.</P>
              <H3>Community Content</H3>
              <P>Posts, comments, and other community contributions may remain on the Platform after account deletion in anonymized form to preserve the integrity of community discussions. If you wish to have specific content removed, please submit a deletion request before closing your account.</P>
              <H3>XP & Activity Records</H3>
              <P>XP transaction logs and activity records are retained for up to 12 months to support dispute resolution and fraud prevention. Aggregated, anonymized analytics data may be retained indefinitely.</P>
              <H3>Financial Records</H3>
              <P>Payment transaction records are retained for 7 years as required by financial regulations. This data is stored securely by our payment processor and is not directly accessible by Toupee4U staff.</P>
              <Callout type="info">You can request a copy of all personal data we hold about you at any time. See "Your Rights" for details.</Callout>
            </Section>
          )}

          {active === 'rights' && (
            <Section title="Your Rights" icon={UserCheck}>
              <P>Depending on your location, you may have certain rights regarding your personal data. We are committed to honoring these rights.</P>
              <div className="space-y-4 mt-2">
                {[
                  { right: 'Right to Access',     desc: 'You can request a copy of the personal data we hold about you at any time through your profile settings or by contacting us.' },
                  { right: 'Right to Correction', desc: 'You can update or correct your account information directly in your profile settings. For data you cannot update yourself, contact us.' },
                  { right: 'Right to Deletion',   desc: 'You can request deletion of your personal data by deleting your account. Certain data may be retained as described in our Data Retention policy.' },
                  { right: 'Right to Portability',desc: 'You can request an export of your data in a machine-readable format. We will process such requests within 30 days.' },
                  { right: 'Right to Object',     desc: 'You may object to certain types of data processing, including profiling. Contact us to exercise this right.' },
                  { right: 'Right to Restrict',   desc: 'In certain circumstances, you may request that we restrict the processing of your personal data while a dispute is resolved.' },
                ].map(item => (
                  <div key={item.right} className="p-4 bg-dark-800 border border-dark-700 rounded-xl">
                    <p className="text-white text-sm font-bold mb-1">{item.right}</p>
                    <p className="text-slate-400 text-sm">{item.desc}</p>
                  </div>
                ))}
              </div>
              <Callout type="info">To exercise any of these rights, contact us through the Platform. We will respond to all requests within 30 days. We may need to verify your identity before processing requests.</Callout>
            </Section>
          )}

          {active === 'cookies' && (
            <Section title="Cookies & Analytics" icon={Cookie}>
              <P>We use cookies and similar tracking technologies to provide and improve our services, analyze usage patterns, and maintain security.</P>
              <H3>Essential Cookies</H3>
              <P>These cookies are necessary for the Platform to function and cannot be disabled. They are used for authentication (keeping you logged in) and security (preventing CSRF attacks).</P>
              <H3>Functional Cookies</H3>
              <P>These cookies remember your preferences and settings, such as your sidebar collapse state and notification preferences. You can disable these through your browser settings, but some features may not work correctly.</P>
              <H3>Analytics</H3>
              <P>We use anonymized analytics to understand how users interact with the Platform. This data is aggregated and does not identify individual users. It helps us improve the Platform experience for everyone.</P>
              <H3>Local Storage</H3>
              <P>We use browser local storage to maintain session state and improve performance. This data is stored locally on your device and is not transmitted to our servers except as part of normal Platform operation.</P>
              <Callout type="info">We do not use advertising cookies or allow third-party advertisers to set cookies on our Platform. Your browsing activity on Toupee4U is not shared with advertising networks.</Callout>
            </Section>
          )}

          {active === 'contact' && (
            <Section title="Contact Us" icon={Mail}>
              <P>If you have questions about this Privacy Policy, want to exercise your data rights, or have concerns about how we handle your personal information, we want to hear from you.</P>
              <H3>How to Reach Us</H3>
              <P>You can contact our privacy team through the Platform's support channels. We aim to respond to all privacy-related inquiries within 5 business days.</P>
              <H3>Policy Updates</H3>
              <P>We may update this Privacy Policy from time to time. When we make material changes, we will notify you via in-app notification or email at least 14 days before the changes take effect. The "Last updated" date at the top of this page indicates when the policy was last revised.</P>
              <H3>Related Policies</H3>
              <div className="flex gap-3 mt-4">
                <Link to="/policy" className="px-4 py-2 bg-dark-700 border border-dark-600 text-slate-300 hover:text-white text-sm font-medium rounded-xl transition-colors">
                  Community Policy
                </Link>
                <Link to="/terms" className="px-4 py-2 bg-dark-700 border border-dark-600 text-slate-300 hover:text-white text-sm font-medium rounded-xl transition-colors">
                  Terms of Service
                </Link>
              </div>
            </Section>
          )}

        </main>
      </div>
    </div>
  );
};

// ── Sub-components ──────────────────────────────────
const Section: React.FC<{ title: string; icon: React.ElementType; children: React.ReactNode }> = ({ title, icon: Icon, children }) => (
  <div className="space-y-4">
    <div className="flex items-start gap-4 pb-6 border-b border-dark-700">
      <div className="w-12 h-12 rounded-2xl bg-dark-800 border border-dark-700 flex items-center justify-center flex-shrink-0">
        <Icon className="w-6 h-6 text-brand-blue" />
      </div>
      <div>
        <h2 className="text-2xl font-extrabold text-white">{title}</h2>
      </div>
    </div>
    <div className="space-y-4">{children}</div>
  </div>
);

const P: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <p className="text-slate-400 text-sm leading-relaxed">{children}</p>
);

const H3: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <h3 className="text-white font-bold text-base mt-6 mb-2">{children}</h3>
);

const Callout: React.FC<{ type: 'info' | 'warning'; children: React.ReactNode }> = ({ type, children }) => (
  <div className={`p-4 rounded-xl border text-sm mt-4 ${
    type === 'info'
      ? 'bg-brand-blue/5 border-brand-blue/20 text-blue-300'
      : 'bg-amber-500/5 border-amber-500/20 text-amber-300'
  }`}>
    {children}
  </div>
);
